---
title: "Filgas A6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
library(censusapi)
library(tidyverse)
library(tigris)
library(sf)
library(leaflet)
library(mapview)
library(survey)

Sys.setenv(CENSUS_KEY="7305c43b014cedd32494ba8e15939faf9f133077")

temp <- tempfile()
download.file("https://www2.census.gov/programs-surveys/acs/data/pums/2019/1-Year/csv_hca.zip",destfile = temp)

pums_hca_2019_1yr <- read_csv(unzip(temp,"psam_h06.csv"))

unlink(temp)
```

```{r}
# pums_2019_1yr <- getCensus(
#   name = "acs/acs1/pums",
#   vintage = 2019,
#   region = "public use microdata area:*",
#   regionin = "state:06",
#   vars = c(
#     "SERIALNO",
#     "SPORDER",
#     "PWGTP",
#     "WGTP",
#     "YBL",
#     "BLD",
#     "TEN",
#     "MV",
#     "HINCP",
#     "AGEP"
#   )
# )
# 
# saveRDS(pums_2019_1yr, "a6_pums.rds")
pums_2019_1yr <- readRDS("a6_pums.rds")
```

```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

leaflet(sf_pumas) %>%
  addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  addPolygons(
    label = sf_pumas$PUMACE10,
    color = "red",
    opacity = 0.5,
    fillOpacity = 0.25,
    weight = 1
  )

sf_pums <- pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)
```

```{r}
sf_pums_clean <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)) %>%
  filter(YBL %in% c("1","2","3")) %>%
  arrange(AGEP) %>%
  group_by(SERIALNO) %>%
  summarize_all(first)

sf_pums_clean <- sf_pums_clean %>%
  mutate(leadrisk = ifelse(HINCP<90000 & AGEP<7, 1, 0)) %>%
  mutate(
    units = BLD %>% 
      factor(
        levels = sf_pums_clean$BLD %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
  ),
  tenure = TEN %>% 
      factor(
        levels = sf_pums_clean$TEN %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
  ),
  moved = MV %>% 
      factor(
        levels = sf_pums_clean$MV %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
        )) %>%
  mutate(
    units = as.numeric(units),
    tenure = as.numeric(tenure),
    moved = as.numeric(moved)
  )
  
  
sf_pums_clean <- sf_pums_clean %>%
  mutate(
  code = PUMA %>% as.numeric(),
  code = code - 7500)

# sf_pums_clean <- sf_pums_clean %>%  
#   code = code %>%
#       factor(
#         levels = sf_pums_clean$code %>%
#           unique() %>%
#           sort()) %>%
#   mutate(code = as.numeric(code))
```

```{r}
logit_model <- glm(
  leadrisk ~ units + tenure + moved + code,
  family = quasibinomial(),
  data = sf_pums_clean
)

summary(logit_model)
         
exp(coef(logit_model))/(exp(coef(logit_model))+1)

#sample_n(sf_pums_clean, 1, replace = FALSE, weight = NULL, .env = NULL)
predict(logit_model, data.frame(units = 2, tenure = 3, moved = 7, code = 6), type = "response")
```

For a building in PUMA 07506 (the South West side of San Francisco) with 2 rental units where the occupants moved in 30 or more years ago, the risk of lead exposure is 1.43%.

```{r}
# HAVE NOT FIGURE OUT THIS PART YET
# 
# pums_2019_1yr_wts <- getCensus(
#   name = "acs/acs1/pums",
#   vintage = 2019,
#   region = "public use microdata area:*", 
#   regionin = "state:06",
#   vars = c(
#     paste0("PWGTP",1:80)
#   )
# ) %>% 
#   mutate(
#     PUMA = str_pad(public_use_microdata_area,5,"left","0")
#   ) %>% 
#   filter(PUMA %in% sf_pums_clean$PUMACE10)
# 
# sf_pums_clean_wts <- pums_2019_1yr_wts %>% 
#   mutate(AGEP = sf_pums_clean$AGEP) %>% 
#   filter(as.numeric(AGEP) >= 5) %>% 
#   select(starts_with("PWGTP"))
# 
# logit_survey_design <- svrepdesign(
#   data = sf_pums_clean,
#   type = "ACS",
#   repweights = sf_pums_clean_wts,
#   weights = ~as.numeric(PWGTP)
# )
# 
# logit_survey_model <- svyglm(
#   formula = leadrisk ~ units + tenure + moved + code,
#   family = quasibinomial(),
#   design = logit_survey_design
# )
# 
# summary(logit_survey_model)
# exp(coef(logit_survey_model))
# predict(logit_survey_model, data.frame(units = 2, tenure = 3, moved = 7, code = 6), type = "response")
# 
# 
# sample <- sample(
#   c(TRUE, FALSE), 
#   nrow(sf_pums_clean), 
#   replace = T, 
#   #prob = c(0.8,0.2)
# )
# 
# train <- sf_pums_clean[sample, ]
# test <- sf_pums_clean[!sample, ]
# 
# train_design <- svrepdesign(
#   data = train,
#   type = "ACS",
#   repweights = sf_pums_clean[sample, ],
#   weights = ~as.numeric(PWGTP)
# )
# 
# train_model <- svyglm(
#   formula = leadrisk ~ units + tenure + moved + code,
#   family = quasibinomial(),
#   design = train_design,
# )
# 
# summary(train_model)
```

